engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 120
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
    - "**.js"
    - "**.jsx"
