FROM    node:latest

RUN     mkdir -p /usr/dist/metabot
COPY    . /usr/dist/metabot
WORKDIR /usr/dist/metabot/

RUN     yarn install

ADD     https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh /usr/dist/metabot/wait-for-it
RUN     chmod +x /usr/dist/metabot/wait-for-it

CMD     ./wait-for-it lavalink:2333 -- yarn run bot
