version: "3.7"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: metabot
    depends_on:
      - lavalink
      - redis
    environment:
      - LAVALINK_HOST=lavalink
      - REDIS_HOST=redis
  lavalink:
    container_name: metabot-lavalink
    image: fredboat/lavalink:master
    environment:
      - SERVER_PORT=2333
      - SERVER_ADDRESS=0.0.0.0
      - LAVALINK_SERVER_PASSWORD=lavalamp
      - LAVALINK_SERVER_WS_PORT=8090
      - LAVALINK_SERVER_WS_HOST=0.0.0.0
      - LAVALINK_SERVER_SOURCES_YOUTUBE=true
      - LAVALINK_SERVER_SOURCES_BANDCAMP=true
      - LAVALINK_SERVER_SOURCES_SOUNDCLOUD=true
      - LAVALINK_SERVER_SOURCES_TWITCH=true
      - LAVALINK_SERVER_SOURCES_VIMEO=true
      - LAVALINK_SERVER_SOURCES_MIXER=true
      - LAVALINK_SERVER_SOURCES_HTTP=true
      - LAVALINK_SERVER_SOURCES_LOCAL=false
      - LAVALINK_SERVER_SENTRY_DNS=
      - LAVALINK_SERVER_BUFFER_DURATION_MS=400
      - LAVALINK_SERVER_YOUTUBE_PLAYLIST_LOAD_LIMIT=600
  redis:
    container_name: metabot-redis
    image: redis
